// <auto-generated />
namespace EmployeeManagment.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetoBirthDateandHireDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetoBirthDateandHireDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201810102159367_update to BirthDate and HireDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
